In [1]:
# Importing the dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
heart_data = pd.read_csv('datasets/heart.csv')

### Expoloring Dataset

In [3]:
heart_data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [4]:
# checking the no. of rows and columns in the dataset
heart_data.shape

(303, 14)

In [5]:
# getting the columns in the dataset
heart_data.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [6]:
# getting some information about the data
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [7]:
# Getting the statistical measures of the dataset
heart_data.describe().T

count        mean        std    min    25%    50%    75%    max
age       303.0   54.366337   9.082101   29.0   47.5   55.0   61.0   77.0
sex       303.0    0.683168   0.466011    0.0    0.0    1.0    1.0    1.0
cp        303.0    0.966997   1.032052    0.0    0.0    1.0    2.0    3.0
trestbps  303.0  131.623762  17.538143   94.0  120.0  130.0  140.0  200.0
chol      303.0  246.264026  51.830751  126.0  211.0  240.0  274.5  564.0
fbs       303.0    0.148515   0.356198    0.0    0.0    0.0    0.0    1.0
restecg   303.0    0.528053   0.525860    0.0    0.0    1.0    1.0    2.0
thalach   303.0  149.646865  22.905161   71.0  133.5  153.0  166.0  202.0
exang     303.0    0.326733   0.469794    0.0    0.0    0.0    1.0    1.0
oldpeak   303.0    1.039604   1.161075    0.0    0.0    0.8    1.6    6.2
slope     303.0    1.399340   0.616226    0.0    1.0    1.0    2.0    2.0
ca        303.0    0.729373   1.022606    0.0    0.0    0.0    1.0    4.0
thal      303.0    2.313531   0.612277    0.0    2.0    2.0    3.0    3.0
target    303.0    0.544554   0.498835    0.0    0.0    1.0    1.0    1.0

In [8]:
# Checking is their any None values in the dataset
heart_data.isna().values.any()

False

In [12]:
heart_data['target'].unique()

array([1, 0], dtype=int64)

In [13]:
# Checking the distribution of the dataset
heart_data.target.value_counts()

1    165
0    138
Name: target, dtype: int64

1 -> Defective Heart

0 -> Healthy Heart

### Splitting the Feature and Target Varibles

In [14]:
X = heart_data.drop('target', axis=1)
y = heart_data['target']

In [19]:
X.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal'],
      dtype='object')

In [20]:
y.name, y.shape

('target', (303,))

In [21]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=0)

In [22]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((212, 13), (91, 13), (212,), (91,))

# Model Building

### 1.) Logistic Regression

In [23]:
from sklearn.linear_model import LogisticRegression

lgr_model = LogisticRegression()

In [24]:
# Training the Logistic Regression model
lgr_model.fit(x_train, y_train)

C:\Users\Aman Rahees\anaconda3\envs\myenv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

#### Logistic Regression model Evaluation

In [25]:
lgr_y_pred = lgr_model.predict(x_test)
lgr_y_pred

array([0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0], dtype=int64)

In [26]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

lgr_accuracy = accuracy_score(y_test, lgr_y_pred)
lgr_precision = precision_score(y_test, lgr_y_pred)
lgr_recall = recall_score(y_test, lgr_y_pred)
lgr_f1score = f1_score(y_test, lgr_y_pred)

In [27]:
confusion_matrix(y_test, lgr_y_pred)

array([[34,  7],
       [ 3, 47]], dtype=int64)

In [28]:
print('Accuracy : {:.2f}%'.format(lgr_accuracy*100))
print('Precision : {:.2f}%'.format(lgr_precision*100))
print('Recall : {:.2f}%'.format(lgr_recall*100))
print('F1 score : {:.2f}%'.format(lgr_f1score*100))

Accuracy : 89.01%
Precision : 87.04%
Recall : 94.00%
F1 score : 90.38%


### 2.) Decision Tree Classifier

In [31]:
from sklearn.tree import DecisionTreeClassifier

classifier_tree = DecisionTreeClassifier()

In [32]:
# Training the Decision Tree Classifier Model
classifier_tree.fit(x_train, y_train)

DecisionTreeClassifier()

#### DecisionTreeClassifier Model Evaluation

In [34]:
tree_y_pred = classifier_tree.predict(x_test)
tree_y_pred

array([0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0], dtype=int64)

In [35]:
tree_accuracy = accuracy_score(y_test, tree_y_pred)
tree_precision = precision_score(y_test, tree_y_pred)
tree_recall = recall_score(y_test, tree_y_pred)
tree_f1score = f1_score(y_test, tree_y_pred)

In [36]:
confusion_matrix(y_test, tree_y_pred)

array([[30, 11],
       [14, 36]], dtype=int64)

In [38]:
print('Accuracy : {:.2f}%'.format(tree_accuracy*100))
print('Precision : {:.2f}%'.format(tree_precision*100))
print('Recall : {:.2f}%'.format(tree_recall*100))
print('F1 score : {:.2f}%'.format(tree_f1score*100))

Accuracy : 72.53%
Precision : 76.60%
Recall : 72.00%
F1 score : 74.23%


### 3.) Support Vector Classifier

In [39]:
from sklearn.svm import SVC

svc_model = SVC(kernel='rbf')

In [40]:
# Training the Support Vecotor classifier 
svc_model.fit(x_train, y_train)

SVC()

In [41]:
svc_y_pred = svc_model.predict(x_test)
svc_y_pred

array([1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1], dtype=int64)

In [42]:
svc_accuracy = accuracy_score(y_test, svc_y_pred)
svc_precision = precision_score(y_test, svc_y_pred)
svc_recall = recall_score(y_test, svc_y_pred)
svc_f1score = f1_score(y_test, svc_y_pred)

In [43]:
confusion_matrix(y_test, svc_y_pred)

array([[19, 22],
       [ 7, 43]], dtype=int64)

In [44]:
print('Accuracy : {:.2f}%'.format(svc_accuracy*100))
print('Precision : {:.2f}%'.format(svc_precision*100))
print('Recall : {:.2f}%'.format(svc_recall*100))
print('F1 score : {:.2f}%'.format(svc_f1score*100))

Accuracy : 68.13%
Precision : 66.15%
Recall : 86.00%
F1 score : 74.78%


# Conclusion

Logistic Regression is best performing among the trained models.

Final Model  -  lgr_model

## Saving the Final model for predictive system

In [45]:
import pickle

filename = 'heart_disease_model.sav'
pickle.dump(lgr_model, open(filename, 'wb'))